Providing a negative value to avoid collisions with non-seed data
System.InvalidOperationException: The seed entity for entity type 'TodoItemEntity' cannot be added because a non-zero value is required for property 'Id'. Consider providing a negative value to avoid collisions with non-seed data.